### ISSUE TITLE
Set up CI/CD pipeline(s)

### ISSUE THREAD

**Issue by pelesh** [ORNL/ReSolve#1]
Set up CI pipelines on Ascent and Deception.

**Comment by ryandanehy** [comment]
We don't currently have a mirror setup for resolve on PNNL gitlab so I can't necessarily get tests working on Deception immediately. So might be best to push that to a future issue, unless @cameronrutherford can help me resolve that.

**Comment by pelesh** [comment]
> We don't currently have a mirror setup for resolve on PNNL gitlab so I can't necessarily get tests working on Deception immediately. So might be best to push that to a future issue, unless @cameronrutherford can help me resolve that.

Let's just start with Ascent, then.

**Comment by ryandanehy** [comment]
Yes. Currently working on it.

**Comment by pelesh** [comment]
Addressed in #4.
