### ISSUE TITLE
Document ReSolve Spack packaging

### ISSUE THREAD

**Issue by pelesh** [ORNL/ReSolve#11]
Add documentation for packaging of ReSolve, including best practices and developer guidelines and standards.

**Comment by pelesh** [comment]
CC @ryandanehy

**Comment by cameronrutherford** [comment]
@ryandanehy how can I add this to our sphinx docs?

**Comment by pelesh** [comment]
> @ryandanehy how can I add this to our sphinx docs?

We have to add Sphinx docs first :). I am yet to make that PR.
