### ISSUE TITLE
CPU Build Requires an Additional Include statement

### ISSUE THREAD

**Issue by ryandanehy** [ORNL/ReSolve#115]
When building from the cpu only cmake preset depending on compiler the following error occurs. 
![Screenshot 2023-12-14 at 12 23 37 PM](https://github.com/ORNL/ReSolve/assets/110119005/4d49cbe3-9ec9-431c-9738-b97d8c73c6db)

Solution is to add 

`#include <cmath>` 

to SystemSolver.cpp

**Comment by cameronrutherford** [comment]
Closed in #116
