### ISSUE TITLE
fix misunderstanding of dimensions in the `Csc` class

### ISSUE THREAD

**Issue by superwhiskers** [ORNL/ReSolve#154]
currently, the way `Csc` is written [assumes that the `n_` parameter inherited from the `Sparse` class is equal to the number of columns](https://github.com/ORNL/ReSolve/blob/develop/resolve/matrix/Csc.cpp#L119-L146), but [this is not true](https://github.com/ORNL/ReSolve/blob/develop/resolve/matrix/Sparse.cpp#L17-L23). this should be fixed before it causes a problem

**Comment by pelesh** [comment]
Thanks for reporting, @superwhiskers. I think this one went under the radar because most of CSC matrix usage is with square matrices.

CC @kswirydo
