### ISSUE TITLE
Add function to expand symmetric matrix stored as an upper/lower triangular to a full square matrix

### ISSUE THREAD

**Issue by pelesh** [ORNL/ReSolve#155]
In some instances an application generating symmetric matrices in a lower/upper triangle storage format may use Re::Solve's LU solvers. In that case, the matrix needs to be expanded to the full square matrix format. It would be helpful to have `expandSymmetricMatrix` function available to make such transformation when needed.

First to decide is where this function should be implemented:
- As a member of `matrix::Sparse` class?
- As a member of `matrix::MatrixHandler`?
- As a standalone function in `matrix` namespace.

Several implementation details that need to be decided:
- When to allocate device memory for the expanded matrix?
- What operations to carry out on the host and what on the device?
- How to reuse sparsity pattern of the expanded matrix over several linear solver calls?

CC @kswirydo @maksud

**Comment by superwhiskers** [comment]
this will be closed by the merge of #164 unless the addition of `ReSolve::matrix::expand` is dropped.

**Comment by superwhiskers** [comment]
actually, i suppose that doesn't totally resolve the issue since `ReSolve::matrix::expand` is currently only host-side. it still needs to be decided whether there's a need for gpu-related functionality here

**Comment by pelesh** [comment]
This issue has been resolved in #184. Feel free to reopen it, if needed.
