### ISSUE TITLE
Add functions to extract L and U factors from LUSOL

### ISSUE THREAD

**Issue by pelesh** [ORNL/ReSolve#159]
Implement following methods in `LinSolverDirectLUSOL` class:
- `getLFactor` and `getUFactor`. Each method should return `matrix::csc` object.
- `getPOrdering` and `getQOrdering`. Methods should return arrays of lengths `n_` and `m_`, respectively.

Implement unit tests for each method.

CC @kswirydo

**Comment by superwhiskers** [comment]
there are some differences in the way i've implemented it, as the closest format for the `U` factor is `matrix::Csr`, not `matrix::Csc`, but it is a correct implementation
