### ISSUE TITLE
Create fortran modules in build directory.

### ISSUE THREAD

**Issue by pelesh** [ORNL/ReSolve#162]
When building LUSOL, Fortran modules are created in the source directory. In order to keep `*.mod` files in the build directory together with other object files, we need to add following line to the LUSOL CMake file:
```cmake
set_target_properties(lusol_lib PROPERTIES Fortran_MODULE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
```

**Comment by pelesh** [comment]
I am unable to reproduce this issue when building Re::Solve from scratch. CMake seems to place Fortran module objects in the build directory where they belong without the instruction above. Unles there are new reports of misplaced Fortran modules, I'll close this issue.

**Comment by superwhiskers** [comment]
this issue doesn't show up on my end either, it may be related to the cmake version or something. either way, i'll close it as not reproducible
