### ISSUE TITLE
`ReSolve::io::writeMatrixToFile` calls `Sparse::print`, which writes out 0-indexed coordinates of matrix data, when the matrix market coordinate format is 1-indexed

### ISSUE THREAD

**Issue by superwhiskers** [ORNL/ReSolve#179]
the implementation of `ReSolve::io::writeMatrixToFormat` writes the [matrix market](https://math.nist.gov/MatrixMarket/formats.html#MMformat) coordinate data as 0-indexed, when it is specified to be 1-indexed. this makes matrix market files generated by resolve unreadable to any matrix market implementation, [including resolve itself](https://github.com/ORNL/ReSolve/blob/develop/resolve/matrix/io.cpp#L50-L55)

**Comment by pelesh** [comment]
We use the print function mainly for debugging and there we want 0-based indices. In #184, I added option to choose 1- or 0-based indexing with 1-based indexing used in matrix export.
