### ISSUE TITLE
convert unscoped enums to scoped enums

### ISSUE THREAD

**Issue by stonecoldhughes** [ORNL/ReSolve#191]
Enumerations in this codebase appear to be unscoped; thus, they are "weakly typed". Scoped enumerations, in contrast, are "strongly typed". This may or may not be desired depending on how these enumerations are used.

scoped/unscoped enum reference:
https://en.cppreference.com/w/cpp/language/enum

A brief treatment of strong vs weak typing.

https://en.wikipedia.org/wiki/Strong_and_weak_typing

**Comment by pelesh** [comment]
Closing for now. If there is a specific action recommended here we can reopen.
