### ISSUE TITLE
Make ReSolve xSDK compliant

### ISSUE THREAD

**Issue by pelesh** [ORNL/ReSolve#2]
This may take a lot of work, but xSDK policies contain some sound software sustainability practices and are good to have implemented anyways. Here is the checklist from xSDK policies [v1.0.0](https://github.com/xsdk-project/xsdk-community-policies/tree/master):
- [x] **M1.** [Support portable installation through Spack.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M1.md)
- [x] **M2.** [Provide a comprehensive test suite for correctness of installation verification.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M2.md)
- [x] **M3.** [Employ user-provided MPI communicator (no MPI_COMM_WORLD). Don't assume a full MPI 3
implementation without checking. Provide an option to prevent any changes to MPI error-handling if it is
changed by default.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M3.md)
- [x] **M4.** [Give best effort at portability to key architectures (standard Linux distributions, GNU, Clang,
vendor compilers, and target machines at ALCF, NERSC, OLCF).](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M4.md)
- [x] **M5.** [Provide a documented, reliable way to contact the development team.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M5.md)
- [x] **M6.** [Respect system resources and settings made by other previously called packages (e.g. signal handling).](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M6.md)
- [x] **M7.** [Come with an open source (BSD style) license.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M7.md)
- [x] **M8.** [Provide a runtime API to return the current version number of the software.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M8.md)
- [x] **M9.** [Use a limited and well-defined symbol, macro, library, and include file name space.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M9.md)
- [x] **M10.** [Provide a publicly available repository.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M10.md)
- [x] **M11.** [Have no hardwired print or IO statements that cannot be turned off.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M11.md)
- [x] **M12.** [For external dependencies, allow installing, building, and linking with an outside copy of external software.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M12.md)
- [x] **M13.** [Install headers and libraries under `<prefix>/include` and `<prefix>/lib`.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M13.md)
- [x] **M14.** [Be buildable using 64 bit pointers. 32 bit is optional.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M14.md)
- [x] **M15.** [All xSDK compatibility changes should be sustainable.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M15.md)
- [x] **M16.** [Have a debug build option.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M16.md)
- [x] **M17.** [Provide sufficient documentation to support use and further development.](https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M17.md)

This is going to be significant team effort. @rcrutherford will coordinate activities and create issues (blocking this one) for specific policies compliances.

**Comment by pelesh** [comment]
Portable installation through Spack delivered in #10

**Comment by cameronrutherford** [comment]
@pelesh we really need a `0.1.0` or equivalent release if we want to try and build for `xSDK` 1.0.0. Is that possible?

**Comment by pelesh** [comment]
The documentation still needs some polishing up, but I think we are there in terms of xSDK compliance. @cameronrutherford  and @ryandanehy, please chime in.

**Comment by cameronrutherford** [comment]
I think we are ready for review

**Comment by pelesh** [comment]
Closing per @cameronrutherford review.

**Comment by cameronrutherford** [comment]
We still need xSDK review and to be included as a part of the list of packages?
