### ISSUE TITLE
Display Ascent arch info in Pipeline Status

### ISSUE THREAD

**Issue by jaelynlitz** [ORNL/ReSolve#24]
Add architecture, compiler, partition info, etc to Ascent pipeline like shown on Deception's

<img width="829" alt="Screenshot 2023-10-25 at 1 17 30 PM" src="https://github.com/ORNL/ReSolve/assets/93339979/a99ee663-4627-4556-8506-fc0081cc814d">

**Comment by pelesh** [comment]
Since Ascent will be out of service soon, this is probably not worth the effort anymore.
