### ISSUE TITLE
Define a Clang-format txt file

### ISSUE THREAD

**Issue by ryandanehy** [ORNL/ReSolve#5]
This file will determine the code format across our repo. This link shows what each variable in the file can change [link](https://zed0.co.uk/clang-format-configurator/)
Below is some of the variables I have defined in respect to the [contributing guidelines](https://code.ornl.gov/ecpcitest/exasgd/resolve/-/blob/develop/CONTRIBUTING.md). 

https://code.ornl.gov/ecpcitest/exasgd/resolve/-/issues/38

**Comment by ryandanehy** [comment]
Language:        Cpp
AccessModifierOffset: 0
AlignConsecutiveMacros: true
BreakBeforeBraces: Attach
ColumnLimit:     150
ConstructorInitializerIndentWidth: 2

See https://zed0.co.uk/clang-format-configurator/ to understand what the default clang-format will also change.
 

[r_KLU_KLU.cpp](https://code.ornl.gov/ecpcitest/exasgd/resolve/uploads/f61b713bf949e6530d5c253d4cf43f13/r_KLU_KLU.cpp)

  

Above is a file I applied the clang-format settings I am thinking of. [@kswirydo](https://github.com/kswirydo) [@peles](https://github.com/peles) let me know your opinion about this styling. It should match the contributing guidelines. If you want you can compare it to the exact r_KLU_KLU.cpp file in the repo.

**Comment by pelesh** [comment]
I think using Gram-Schmidt or FGMRES class would give us better test case.

**Comment by pelesh** [comment]
Re-opening this as we still have to fine-tune a few formatting details.
