### ISSUE TITLE
Include files not copied to the install directory

### ISSUE THREAD

**Issue by maksud** [ORNL/ReSolve#60]
When `make install` is executed, the HIP related header files are not copied to the install folder. e.g. hip_check_errors.hpp, LinSolverDirectRocSolverRf.hpp etc.

**Comment by pelesh** [comment]
@maksud, I did a fresh install and I can see both files:
```
include/resolve/LinSolverDirectRocSolverRf.hpp
include/resolve/hip/hip_check_errors.hpp
```
Could you check out, build and install the latest `hip-first-take-dev` and see if the issue persists?

**Comment by cameronrutherford** [comment]
#53 fixed this - feel free to re-open if you find otherwise
