### ISSUE TITLE
Missing header file include in the installed include files 

### ISSUE THREAD

**Issue by maksud** [ORNL/ReSolve#72]
For the HIP version:
The include file `resolve/LinSolverDirectRocSolverRf.hpp` needs to add `#include <resolve/matrix/Csr.hpp>`.

For the CUDA version:
The include file `resolve/LinSolverDirectCuSolverGLU.hpp` needs to add `#include <resolve/workspace/LinAlgWorkspace.hpp>`

**Comment by pelesh** [comment]
Please add missing headers to the source files and use forward declarations in the headers.

**Comment by pelesh** [comment]
CC @kswirydo
