### ISSUE TITLE
Document CI/CD configurations and build scripts

### ISSUE THREAD

**Issue by pelesh** [ORNL/ReSolve#75]
Create four README files for:
- [ ] GitHub runners
- [ ] GitLab runners
- [ ] Build scripts
- [ ] Spack package configurations

Probably a good idea to create markdown or ReST files with documentation in respective directories.

**Comment by cameronrutherford** [comment]
Also need to write small workflow guides when you might want to:
- Rebuild resolve deps
- Update resolve spack package / add a new version
- Refresh secrets / modify GitHub workflows files to change behavior

**Comment by cameronrutherford** [comment]
I am pausing work on this until #44 is merged. cc @ryandanehy

**Comment by pelesh** [comment]
> I am pausing work on this until #44 is merged. cc @ryandanehy

@cameronrutherford, it is merged. We can continue 😉

**Comment by pelesh** [comment]
@cameronrutherford, @ryandanehy: Please see also #80, which is related to this issue, and suggest how to handle it.
